services:
  r2-database:
    container_name: r2_database
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "0:0"
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - r2_sqldata:/var/opt/mssql/data
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1", "-No"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - r2-network

  r2-ui:
    container_name: r2_ui
    image: ghcr.io/valentinwlt/r2:latest
    user: "0:0"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=r2-database;Database=RessourcesRelationnelles;User Id=sa;Password=R2SecurePass123!;TrustServerCertificate=true;
    ports:
      - "8080:8080"
    depends_on:
      r2-database:
        condition: service_healthy
    networks:
      - r2-network

volumes:
  r2_sqldata:

networks:
  r2-network:
    driver: bridge