services:
  r2-database:
    container_name: r2_database
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "0:0"
    environment:
      SA_PASSWORD: "R2SecurePass123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - r2_sqldata:/var/opt/mssql/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P R2SecurePass123! -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - r2-network

  r2-ui:
    container_name: r2_ui
    build:
      context: .
      dockerfile: R2.UI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=r2-database;Database=RessourcesRelationnelles;User Id=sa;Password=R2SecurePass123!;TrustServerCertificate=true;
    ports:
      - "8080:8080"
    depends_on:
      r2-database:
        condition: service_healthy
    networks:
      - r2-network

volumes:
  r2_sqldata:

networks:
  r2-network:
    driver: bridge