services:
  r2-database:
    container_name: r2_database_prod
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "0:0"
    environment:
      SA_PASSWORD: "${DB_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - r2_sqldata_prod:/var/opt/mssql/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${DB_SA_PASSWORD} -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - r2-network
    restart: unless-stopped

  r2-ui:
    container_name: r2_ui_prod
    image: ghcr.io/davidlaclef/ressourcesrelationnelles:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=r2-database;Database=RessourcesRelationnelles;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=true;
    ports:
      - "80:8080"
    depends_on:
      r2-database:
        condition: service_healthy
    networks:
      - r2-network
    restart: unless-stopped

volumes:
  r2_sqldata_prod:

networks:
  r2-network:
    driver: bridge