name: 01-2 - SonarQube

on:
  workflow_call

jobs:
  SonarQube:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dotnet-coverage-report
          path: coverage

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: SonarQube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"${{ github.repository_owner }}_RessourcesRelationnelles" \
            /o:"${{ github.repository_owner }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage/*.opencover.xml"
          
          dotnet build
          
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"