name: 01-2 - Integration SonarQube

on:
  workflow_call

jobs:
  QualityDotNet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-coverage-report
          path: ./coverage

      - name: Install SonarCloud scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"${{ github.repository_owner }}_ressources-relationnelles" \
            /o:"${{ github.repository_owner }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="coverage/**/coverage.opencover.xml"
          
          dotnet build --configuration Release
          
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"